version: "3.3"

services:
  shipper:
    build:
      context: shipper
    volumes:
      - ./shipper:/apt
    ports:
      - 20777:20777

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

  influxdb:
    image: influxdb:1.7

volumes:
  grafana_data:
